sudo: required

notifications:
  email: false

language: cpp 

env:
# All commented images take too long to build on Travis, making them less useful
  - BUILD_VER=master BUILD_TYPE=release  	BUILD_DEP=clang-mpi-fulldepsmanual
  - BUILD_VER=master BUILD_TYPE=debug    	BUILD_DEP=clang-mpi-fulldepsmanual
# - BUILD_VER=master BUILD_TYPE=debugrelease    BUILD_DEP=clang-mpi-fulldepsmanual

  - BUILD_VER=master BUILD_TYPE=debug    	BUILD_DEP=gcc-serial-bare
  - BUILD_VER=master BUILD_TYPE=release  	BUILD_DEP=gcc-serial-bare
# - BUILD_VER=master BUILD_TYPE=debugrelease  	BUILD_DEP=gcc-serial-bare

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install docker-engine
  # These images are built externally, not on Travis. Assume they are available.
  - touch locks/base-clang-mpi locks/full-deps-fulldepsmanual locks/base-gcc-serial
  make RELEASES=$BUILD_VER DEPS=$BUILD_DEP BUILDS=$BUILD_TYPE dealii 
script:
  - echo "Built dealii/dealii:$BUILD_VER-$BUILD_DEP-$BUILD_TYPE docker image."

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ -d dealii/$TAG_NAME ]; then
         docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
         docker push dealii/dealii:$BUILD_VER-$BUILD_DEP-$BUILD_TYPE
      fi
    fi
