sudo: required

notifications:
  email: false

language: cpp 

env:
# All commented images take too long to build on Travis, making them less useful
# - BUILD_TYPE=release         BUILD_DEP=gcc-mpi-fulldepsmanual
# - BUILD_TYPE=debug           BUILD_DEP=gcc-mpi-fulldepsmanual
# - BUILD_TYPE=debugrelease    BUILD_DEP=gcc-mpi-fulldepsmanual

  - BUILD_TYPE=debug           BUILD_DEP=clang-serial-bare
  - BUILD_TYPE=release         BUILD_DEP=clang-serial-bare
# - BUILD_TYPE=debugrelease    BUILD_DEP=clang-serial-bare

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install docker-engine
  # These images are built externally, not on Travis. Assume they are available.
  - cd locks; touch base-gcc-mpi  base-gcc-serial  base-clang-serial; cd ..
  - cd locks; touch full-deps-fulldepsmanual full-deps-fulldepscandi; cd ..
  - export DEAL_II_REL=`git ls-remote https://github.com/dealii/dealii HEAD | cut -c1-7`
  - make RELEASES=$DEAL_II_REL DEPS=$BUILD_DEP BUILDS=$BUILD_TYPE dealii 
script:
  - echo "Built dealii/dealii:$BUILD_VER-$BUILD_DEP-$BUILD_TYPE docker image."

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push dealii/dealii:`git show-ref --hash --abbrev HEAD`-$BUILD_DEP-$BUILD_TYPE
    fi;
